### ISSUE TITLE
How to add more than one database to someuser?

### ISSUE THREAD

**Issue by nexudx** [debops/ansible-mariadb#35]
Your example shows this simple configuration. But how can i add this user a list of databases?

mariadb__users:

  - name: 'someuser'
    database: 'somedatabase'
    priv_aux: False

**Comment by drybjed** [comment]
You can find an example of multiple databases in https://github.com/debops/ansible-mariadb/issues/34

**Comment by nexudx** [comment]
My fault. Thanks!
